# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '5432:5432'

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"

    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16